language: python
sudo: false
python:
  - 3.5

cache:
  directories:
    - $HOME/.cache/pip

env:
    - TOXENV=d18-py27
    - TOXENV=d18-py33
    - TOXENV=d18-py34
    - TOXENV=d18-py35
    - TOXENV=d18-pypy

    - TOXENV=d19-py27
    - TOXENV=d19-py34
    - TOXENV=d19-py35
    - TOXENV=d19-pypy

    - TOXENV=d110-py27
    - TOXENV=d110-py34
    - TOXENV=d110-py35
    - TOXENV=d110-pypy

    - TOXENV=d111-py27
    - TOXENV=d111-py34
    - TOXENV=d111-py35
    - TOXENV=d111-pypy

    - TOXENV=ddev-py35
    - TOXENV=ddev-pypy


matrix:
  allow_failures:
    - env: TOXENV=ddev-py27
    - env: TOXENV=ddev-py34
    - env: TOXENV=ddev-py35
    - env: TOXENV=ddev-pypy


install:
  - pip install -e ".[test]"

script:
  - tox -e $TOXENV -- py.test tests -vv --capture=no --cov=adminactions --cov-report= --cov-config=tests/.coveragerc

before_success:
  - coverage erase

after_success:
  - coverage combine
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/825f521b72e421171f8e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
